export type AuthLocale = 'ru' | 'en'
export const AUTH_LOCALE_KEY = 'elevenhouse.auth.locale'

// Russian messages are stable keys, including messages already stored in form state.
// Resolve at render time so changing language never resets a challenge or user input.
export const englishCopy: Record<string, string> = {
  'Регистрация': 'Sign up',
  'Вход': 'Sign in',
  'Кабинет уже существует': 'Workspace already exists',
  'Кабинет не найден': 'Workspace not found',
  'Не удалось подключиться': 'Unable to connect',
  'Не удалось продолжить': 'Unable to continue',
  'Коды запрашиваются слишком часто': 'Code requests are too frequent',
  'Попробуйте ещё раз. Если проблема повторится, обратитесь в поддержку.': 'Please try again. If the problem continues, contact support.',
  'Код не подошёл': 'That code did not match',
  'Проверьте цифры и попробуйте ещё раз.': 'Check the digits and try again.',
  'Код не подошёл. Проверьте цифры.': 'That code did not match. Check the digits.',
  'Запросите новый код и продолжите с этого шага.': 'Request a new code and continue from this step.',
  'Подождите немного и попробуйте запросить код ещё раз.': 'Wait a moment before requesting another code.',
  'Проверьте интернет и попробуйте ещё раз. Введённые данные сохранены в форме.': 'Check your connection and try again. Your details are still in the form.',
  'Нам нужна небольшая пауза': 'We need a moment',
  'Сервис временно недоступен. Попробуйте ещё раз через несколько минут.': 'The service is temporarily unavailable. Please try again in a few minutes.',
  'У вас уже есть кабинет': 'You already have a workspace',
  'Перейдите ко входу — повторно создавать кабинет не нужно.': 'Sign in to your existing workspace. There is no need to create another one.',
  'Проверьте контакт или создайте новый кабинет.': 'Check your contact details or create a new workspace.',
  'Доступ к кабинету ограничен': 'Workspace access is restricted',
  'Откройте помощь, чтобы узнать, как восстановить доступ.': 'Open sign-in help to find out how to recover access.',
  'Подтверждение': 'Verification',
  'Добро пожаловать': 'Welcome',
  'Помощь со входом': 'Sign-in help',
  'Создать кабинет': 'Create workspace',
  'Войти в кабинет': 'Sign in to workspace',
  'Соединение восстановлено. Можно продолжить.': 'Connection restored. You can continue.',
  'Проверяем код…': 'Verifying code…',
  'Отправляем код…': 'Sending code…',
  'на почту': 'by email',
  'на телефон': 'to your phone',
  'Контакт подтверждён.': 'Contact verified.',
  'Слишком много попыток. Запросите новый код через минуту.': 'Too many attempts. Request a new code in one minute.',
  'Новый код отправлен. Используйте последнее сообщение.': 'A new code has been sent. Use the most recent message.',
  'Подскажите, как к вам обращаться.': 'Please enter your name.',
  'Проверьте адрес. Например, anna@example.com.': 'Check the address. For example, anna@example.com.',
  'Имя должно быть от 2 до 200 символов.': 'Your name must be between 2 and 200 characters.',
  'Сообщение задерживается?': 'Is your message taking a while?',
  'Проверьте папку «Спам» и правильность адреса. Затем запросите новый код или измените контакт.': 'Check your spam folder and email address. Then request a new code or change your contact.',
  'Войдите ещё раз': 'Please sign in again',
  'Сессия завершилась. Получите новый код, чтобы вернуться в кабинет.': 'Your session has expired. Get a new code to return to your workspace.',
  'Проверьте почту': 'Check your email',
  'Вы на своём месте': 'Make yourself at home',
  'Поможем вернуться': 'Let’s get you back in',
  'Проверьте телефон': 'Check your phone',
  'Перейти к форме': 'Skip to the form',
  'ElevenHouse — на главную': 'ElevenHouse — home',
  'На главную': 'Home',
  'Всё начинается': 'It all starts',
  'с': 'with',
  'вас': 'you',
  'Ваши знания становятся системой.': 'Your knowledge becomes a system.',
  'А у вас появляется пространство для самого важного.': 'And you find the space for what matters most.',
  'для самого важного.': 'for what matters most.',
  'Место, где ваша': 'A place where your',
  'практика обретает форму.': 'practice takes shape.',
  'Возможности ElevenHouse': 'ElevenHouse features',
  'Ваши знания': 'Your knowledge',
  'Ваши клиенты': 'Your clients',
  'Ваша система': 'Your system',
  'Вход и регистрация': 'Sign in and sign up',
  'ЛИЧНЫЙ КАБИНЕТ': 'YOUR WORKSPACE',
  'Выберите действие': 'Choose an action',
  'Изменить контакт': 'Change contact',
  'Вернуться ко входу': 'Back to sign in',
  'Для начала — только имя и контакт.\nБесплатно, без карты.': 'Just your name and contact to get started.\nFree, no card required.',
  'Клиенты, планы и ваши идеи уже ждут.\nВойдите по коду — пароль не нужен.': 'Your clients, plans and ideas are waiting.\nSign in with a code. No password needed.',
  'Код из': 'A',
  'цифр отправлен': 'digit code has been sent',
  'на номер': 'to your phone',
  'Даже если привычный способ входа больше не работает.': 'Even if your usual way of signing in no longer works.',
  'Перейти ко входу': 'Go to sign in',
  'Как к вам обращаться': 'What should we call you?',
  'Ваше имя': 'Your name',
  'Электронная почта': 'Email address',
  'Номер телефона': 'Phone number',
  'По телефону': 'Use phone',
  'По почте': 'Use email',
  'Код страны': 'Country code',
  'Пришлём код': 'We’ll send a code',
  'в SMS': 'by SMS',
  '. Запоминать пароль не нужно.': '. No password to remember.',
  'Отправляем код': 'Sending code',
  'Попробовать ещё раз': 'Try again',
  'Создать своё пространство': 'Create your workspace',
  'Войти по коду': 'Sign in with a code',
  'Только вы получаете доступ к кабинету': 'Only you get access to your workspace',
  'Код подтверждения': 'Verification code',
  'Запросите новый код ниже.': 'Request a new code below.',
  'Слишком много попыток': 'Too many attempts',
  'Время действия кода истекло': 'This code has expired',
  'Подождите немного, затем запросите новый код.': 'Wait a moment, then request a new code.',
  'Теперь можно запросить новый код.': 'You can now request a new code.',
  'Это бывает. Получите новый код и продолжите с этого шага.': 'It happens. Get a new code and continue from here.',
  'Проверяем код': 'Verifying code',
  'Отправляем новый код…': 'Sending a new code…',
  'Отправить новый код': 'Send a new code',
  'Не получается найти код?': 'Can’t find your code?',
  'Проверьте папку «Спам» и адрес выше. Письмо может идти несколько минут. Можно отправить новый код или изменить контакт.': 'Check your spam folder and the address above. Delivery may take a few minutes. You can request a new code or change your contact.',
  'Проверьте номер и приём SMS. Сообщение может идти несколько минут. Можно отправить новый код или изменить контакт.': 'Check your number and SMS reception. Delivery may take a few minutes. You can request a new code or change your contact.',
  'Код не приходит?': 'Haven’t received a code?',
  'Есть другой контакт?': 'Have another contact?',
  'Войдите через почту или телефон, уже привязанные к вашему кабинету.': 'Use an email address or phone number already linked to your workspace.',
  'Выбрать другой способ': 'Choose another method',
  'Нет доступа к почте и телефону?': 'Can’t access your email or phone?',
  'Восстановите доступ к почте у почтового провайдера или к номеру у оператора. Если это невозможно, обратитесь в поддержку через действующее приложение.': 'Recover your email through your email provider, or your number through your mobile operator. If that is not possible, contact support through the live application.',
  'Открыть ElevenHouse': 'Open ElevenHouse',
  'Никому не сообщайте код подтверждения, даже если собеседник представляется поддержкой.': 'Never share your verification code, even with someone claiming to be support.',
  'Не удаётся войти?': 'Having trouble signing in?',
  'Уже есть своё пространство?': 'Already have a workspace?',
  'Ещё нет кабинета?': 'New to ElevenHouse?',
  'Помощь': 'Get help',
  'Войти': 'Sign in',
  'Создать': 'Sign up',
  'Меньше рутины. Больше места для вашего дела.': 'Less routine. More space for your practice.',
  'В своём ритме. В своём пространстве.': 'Your pace. Your space.',
  'ВАША ПРАКТИКА. ВАШ МАСШТАБ.': 'YOUR PRACTICE. YOUR POTENTIAL.',
  'Россия': 'Russia', 'Беларусь': 'Belarus', 'Казахстан': 'Kazakhstan',
  'Кыргызстан': 'Kyrgyzstan', 'Армения': 'Armenia', 'Азербайджан': 'Azerbaijan',
  'Молдова': 'Moldova', 'Таджикистан': 'Tajikistan', 'Узбекистан': 'Uzbekistan',
  'Туркменистан': 'Turkmenistan', 'Грузия': 'Georgia',
  'Введите электронную почту.': 'Enter your email address.',
  'Введите номер телефона.': 'Enter your phone number.',
  'Язык интерфейса': 'Interface language',
}

const dynamicCopy: [RegExp, (...values: string[]) => string][] = [
  [/^Повторить через (\d+) сек\.$/, (seconds) => `Try again in ${seconds} sec.`],
  [/^Отправить повторно через (\d+) сек\.$/, (seconds) => `Send again in ${seconds} sec.`],
  [/^Код действует (\d+:\d+)$/, (time) => `Code expires in ${time}`],
  [/^Код не подошёл\. Проверьте цифры\. Осталось попыток: (\d+)\.$/, (count) => `That code did not match. Check the digits. Attempts left: ${count}.`],
  [/^Проверьте код страны и (\d+) цифр номера\.$/, (count) => `Check the country code and the ${count}-digit phone number.`],
  [/^Введите все (\d+) цифр из сообщения\.$/, (count) => `Enter all ${count} digits from the message.`],
  [/^Код отправлен (на почту|на телефон) (.+)\.$/, (channel, contact) => `Code sent ${channel === 'на почту' ? 'by email to' : 'to phone'} ${contact}.`],
]

export function translateAuth(text: string, locale: AuthLocale): string {
  if (locale === 'ru' || !text) return text
  const trimmed = text.trim()
  const direct = englishCopy[trimmed]
  if (direct) return text.replace(trimmed, () => direct)
  for (const [pattern, format] of dynamicCopy) {
    const match = trimmed.match(pattern)
    if (match) return text.replace(trimmed, () => format(...match.slice(1)))
  }
  return text
}

export function resolveLocale(query: string | null, saved: string | null, browserLanguage: string): AuthLocale {
  if (query === 'ru' || query === 'en') return query
  if (saved === 'ru' || saved === 'en') return saved
  return browserLanguage.toLowerCase().split('-')[0] === 'en' ? 'en' : 'ru'
}
